<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <AssemblyName>ObbyistMacro</AssemblyName>
    <RootNamespace>ObbyistMacro</RootNamespace>
    <ApplicationIcon>..\ObbyiestMacro.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Version>2.0.0</Version>
    <Product>ObbyistMacro</Product>
    <Authors>Obbyist</Authors>
    <Description>Professional Roblox obbies macro toolkit - FPS changer, Wallhop and Freeze macros.</Description>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
    <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="..\ObbyiestMacro.ico" />
    <Resource Include="assets\logo_256.png" />
  </ItemGroup>

</Project>